//signIn
export const SIGNIN_TRIGGER = 'SIGNIN_TRIGGER';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAIL = 'SIGNIN_FAIL';

//getSchoolLoginData
export const GET_SCHOOL_LOGIN_DATA_TRIGGER = 'GET_SCHOOL_LOGIN_DATA_TRIGGER';
export const GET_SCHOOL_LOGIN_DATA_SUCCESS = 'GET_SCHOOL_LOGIN_DATA_SUCCESS';
export const GET_SCHOOL_LOGIN_DATA_FAIL = 'GET_SCHOOL_LOGIN_DATA_FAIL';

//getAllGroups
export const GET_ALL_GROUPS_TRIGGER = 'GET_ALL_GROUPS_TRIGGER';
export const GET_ALL_GROUPS_SUCCESS = 'GET_ALL_GROUPS_SUCCESS';
export const GET_ALL_GROUPS_FAIL = 'GET_ALL_GROUPS_FAIL';

//getAllPermissions
export const GET_ALL_PERMISSIONS_TRIGGER = 'GET_ALL_PERMISSIONS_TRIGGER';
export const GET_ALL_PERMISSIONS_SUCCESS = 'GET_ALL_PERMISSIONS_SUCCESS';
export const GET_ALL_PERMISSIONS_FAIL = 'GET_ALL_PERMISSIONS_FAIL';

