//signIn
export const SIGNIN_TRIGGER = 'SIGNIN_TRIGGER';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAIL = 'SIGNIN_FAIL';

//getSchoolLoginData
export const GET_SCHOOL_LOGIN_DATA_TRIGGER = 'GET_SCHOOL_LOGIN_DATA_TRIGGER';
export const GET_SCHOOL_LOGIN_DATA_SUCCESS = 'GET_SCHOOL_LOGIN_DATA_SUCCESS';
export const GET_SCHOOL_LOGIN_DATA_FAIL = 'GET_SCHOOL_LOGIN_DATA_FAIL';

//getAllGroups
export const GET_ALL_GROUPS_TRIGGER = 'GET_ALL_GROUPS_TRIGGER';
export const GET_ALL_GROUPS_SUCCESS = 'GET_ALL_GROUPS_SUCCESS';
export const GET_ALL_GROUPS_FAIL = 'GET_ALL_GROUPS_FAIL';

//getAllPermissions
export const GET_ALL_PERMISSIONS_TRIGGER = 'GET_ALL_PERMISSIONS_TRIGGER';
export const GET_ALL_PERMISSIONS_SUCCESS = 'GET_ALL_PERMISSIONS_SUCCESS';
export const GET_ALL_PERMISSIONS_FAIL = 'GET_ALL_PERMISSIONS_FAIL';

//getGroupUsers
export const GET_GROUP_USERS_TRIGGER = 'GET_GROUP_USERS_TRIGGER';
export const GET_GROUP_USERS_SUCCESS = 'GET_GROUP_USERS_SUCCESS';
export const GET_GROUP_USERS_FAIL = 'GET_GROUP_USERS_FAIL';

//removeUserFromGroup
export const REMOVE_USER_FROM_GROUP_TRIGGER = 'REMOVE_USER_FROM_GROUP_TRIGGER';
export const REMOVE_USER_FROM_GROUP_SUCCESS = 'REMOVE_USER_FROM_GROUP_SUCCESS';
export const REMOVE_USER_FROM_GROUP_FAIL = 'REMOVE_USER_FROM_GROUP_FAIL';

//addUserToGroup
export const ADD_USER_TO_GROUP_TRIGGER = 'ADD_USER_TO_GROUP_TRIGGER';
export const ADD_USER_TO_GROUP_SUCCESS = 'ADD_USER_TO_GROUP_SUCCESS';
export const ADD_USER_TO_GROUP_FAIL = 'ADD_USER_TO_GROUP_FAIL';

//deleteGroupAsAdmin
export const DELETE_GROUP_TRIGGER = 'DELETE_GROUP_TRIGGER';
export const DELETE_GROUP_SUCCESS = 'DELETE_GROUP_SUCCESS';
export const DELETE_GROUP_FAIL = 'DELETE_GROUP_FAIL';

//createNewGroupASAdmin
export const CREATE_NEW_GROUP_TRIGGER = 'CREATE_NEW_GROUP_TRIGGER';
export const CREATE_NEW_GROUP_SUCCESS = 'CREATE_NEW_GROUP_SUCCESS';
export const CREATE_NEW_GROUP_FAIL = 'CREATE_NEW_GROUP_FAIL';

//editGroupName
export const EDIT_GROUP_NAME_TRIGGER = 'EDIT_GROUP_NAME_TRIGGER';
export const EDIT_GROUP_NAME_SUCCESS = 'EDIT_GROUP_NAME_SUCCESS';
export const EDIT_GROUP_NAME_FAIL = 'EDIT_GROUP_NAME_FAIL';

//addPermissionToGroup
export const ADD_PERMISSION_TO_GROUP_TRIGGER = 'ADD_PERMISSION_TO_GROUP_TRIGGER';
export const ADD_PERMISSION_TO_GROUP_SUCCESS = 'ADD_PERMISSION_TO_GROUP_SUCCESS';
export const ADD_PERMISSION_TO_GROUP_FAIL = 'ADD_PERMISSION_TO_GROUP_FAIL';

//listAllUsers 
export const LIST_ALL_USERS_TRIGGER = 'LIST_ALL_USERS_TRIGGER';
export const LIST_ALL_USERS_SUCCESS = 'LIST_ALL_USERS_SUCCESS';
export const LIST_ALL_USERS_FAIL = 'LIST_ALL_USERS_FAIL';
